### ISSUE TITLE
firebase issue causing app to crash

### ISSUE THREAD

**Issue by ATY-07** [pkini2002/AR-Ecommerce-App#25]
firebase issue crashing app , can u please fix it 

![GG](https://github.com/pkini2002/AR-Ecommerce-App/assets/112961240/8e109609-2bc5-412a-8aa0-543aa25e7792)

2024-04-25 23:14:18.333  7438-7438  AndroidRuntime          com.example.ar_ecommerce             E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.ar_ecommerce, PID: 7438
                                                                                                    java.lang.NullPointerException: Can't pass null for argument 'pathString' in child()
                                                                                                    	at com.google.firebase.database.DatabaseReference.child(DatabaseReference.java:96)
                                                                                                    	at com.google.firebase.database.DataSnapshot.child(DataSnapshot.java:64)
                                                                                                    	at com.example.ar_ecommerce.MainActivity$8.onDataChange(MainActivity.java:165)
                                                                                                    	at com.google.firebase.database.Query$1.onDataChange(Query.java:191)
                                                                                                    	at com.google.firebase.database.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:75)
                                                                                                    	at com.google.firebase.database.core.view.DataEvent.fire(DataEvent.java:63)
                                                                                                    	at com.google.firebase.database.core.view.EventRaiser$1.run(EventRaiser.java:55)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
2024-04-25 23:14:27.986  7438-7444  art                     com.example.ar_ecommerce             I  Debugger is no longer active
2024-04-25 23:14:27.986  7438-7444  art                     com.example.ar_ecommerce             I  Starting a blocking GC Instrumentation

**Comment by Mudit-pip** [comment]
is this issue still relevant?
May i get any additional info for this issue.

**Comment by Navinn7** [comment]
Can you please fix this issue
